### ISSUE TITLE
[QUESTION] Tailwind (Nativewind) not working

### ISSUE THREAD

**Issue by asiflhr** [svbutko/react-native-template-strong#109]
Tailwind (Nativewind) Css not working with this template, Need Help!

**Comment by svbutko** [comment]
Hello, I'm at this moment updating this template to support latest dependency versions (including RN 0.72) in [this PR](https://github.com/svbutko/react-native-template-strong/pull/108)

I'll try to connect it there and will come back with answe

Check whether you installed NativeWind properly according to this page:
https://www.nativewind.dev/quick-starts/react-native-cli

**Comment by asiflhr** [comment]
Hey @svbutko, I hope you will be fine.
Yep, I followed that link's: [https://www.nativewind.dev/quick-starts/react-native-cli](url) instructions.

Here are my tailwind and babel config files, I'm following your file structure, and applying nativewind styles in **Main.tsx** file.

**tailwind.config.js**
`/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}", "./<custom-folder>/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
`

**babel.config.js**
`module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: ["nativewind/babel"],
  // env: {
  //   test: {
  //     plugins: ["react-native-config-node/transform"],
  //   },
  //   production: {
  //     plugins: ["transform-remove-console"],
  //   },
  // },
};
`

**Main.tsx**
`import {NavigationFunctionComponent} from "react-native-navigation";
import {ScrollView, Text, View} from "react-native";
import React from "react";
import {localization} from "../../common/localization/localization";
import {CommonStyles} from "../../core/theme/commonStyles";

export const Main: NavigationFunctionComponent = (): JSX.Element => {
  return (
    <ScrollView testID={"MainPageID"} contentInsetAdjustmentBehavior={"automatic"}>
      <View className="flex flex-col w-full h-full justify-center items-center">
        <Text className="w-full text-center text-3xl font-bold text-green-600">Main</Text>
      </View>
    </ScrollView>
  );
};

Main.options = {
  topBar: {
    largeTitle: {
      visible: true,
    },
    title: {
      text: localization.pages.main,
    },
  },
};
`

**Comment by asiflhr** [comment]
Am I doing something wrong?

**Comment by svbutko** [comment]
@asiflhr, I tried to connect it and it works without issues:

1. Added `"nativewind": "2.0.11"` to `dependencies`
2. Added `"tailwindcss": "3.3.2"` to `devDependencies`
3. Modified `babel.config.json`:
```module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['nativewind/babel', 'react-native-reanimated/plugin'],
  env: {
    test: {
      plugins: ['react-native-config-node/transform'],
    },
    production: {
      plugins: ['transform-remove-console'],
    },
  },
};
```
4. Generated `tailwind.config.js` with this content:
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};
```
5. And tested it:
```
import {styled} from 'nativewind';

const StyledView = styled(View);

export const TvList: NavigationFunctionComponent = () => {
  return <StyledView className={`flex-1 bg-amber-500`} />;
};
```

![image](https://github.com/svbutko/react-native-template-strong/assets/14828004/ef8c324e-1919-4753-ad5b-8e5b69330863)
