### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Nadimkhan120** [svbutko/react-native-template-strong#77]
hi @svbutko , amazing work you have done, can you please create an example project to show how to use all the features.
and when will you complete the pending issues you have opened. thanks

**Comment by svbutko** [comment]
> hi @svbutko , amazing work you have done, can you please create an example project to show how to use all the features. and when will you complete the pending issues you have opened. thanks

Hi, yeah it's part of issues I created, there's a dedicated issue for that: https://github.com/svbutko/react-native-template-strong/issues/29#issue-1014128388

I have an idea of a small application which will include most of the features and they way I intended them to be used in first place (like how I see it)

**Comment by svbutko** [comment]
I'll close this one so that the conversation continue in that issue, I'll mention more stuff later about it there
