### ISSUE TITLE
Error while run npm install

### ISSUE THREAD

**Issue by codeCleanDev** [svbutko/react-native-template-strong#78]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test_strong@1.0.0
npm ERR! Found: react-native@0.66.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.66.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.64" from react-native-localization@2.1.7
npm ERR! node_modules/react-native-localization
npm ERR!   react-native-localization@"2.1.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by a-eid** [comment]
use `npm install --force`
