### ISSUE TITLE
[BUG] Failed on Mac with RN red screen after start

### ISSUE THREAD

**Issue by sytolk** [svbutko/react-native-template-strong#84]
**Describe the bug**

```
E  ./index.js 

error: node_modules/react-native-gesture-handler/src/handlers/gestures/pinchGesture.ts: /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/react-native-gesture-handler/src/handlers/gestures/pinchGesture.ts: Cannot find module '@babel/plugin-transform-shorthand-properties'
Require stack:
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/@babel/core/lib/config/files/index.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/@babel/core/lib/index.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/react-native-reanimated/plugin.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/config/files/index.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/index.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/metro-react-native-babel-transformer/src/index.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/metro-transform-worker/src/index.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/metro/node_modules/jest-worker/build/workers/processChild.js
```

**To Reproduce**
1.  `npx react-native init MyApp --template react-native-template-strong`
2.  `npm install --force`
3.  `npx pod-install`
4.  `start-reset-cache`
5.  `npm run-script ios:run`

**Desktop (please complete the following information):**
 - OS: 
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52
 - Template Version [e.g. 1.0.0] latest

**Comment by sytolk** [comment]
after install with `npm install --save-dev @babel/plugin-transform-shorthand-properties`
next error:
`error: node_modules/react-native-gesture-handler/src/handlers/gestures/pinchGesture.ts: /Users/sytolk/IdeaProjects/MyTemplateApp/MyTemplateApp/node_modules/react-native-gesture-handler/src/handlers/gestures/pinchGesture.ts: Cannot find module '@babel/plugin-transform-arrow-functions'`

**Comment by svbutko** [comment]
@sytolk

Hi, sorry for late answer, can you try to update `react-native-gesture-handler`, `@babel/core` and `@babel/runtime` to the latest version?


It should be already fixed in there and won't require addition of `@babel/plugin-transform-shorthand-properties`

Tried it with new set of updated dependencies [from here](https://github.com/svbutko/react-native-template-strong/pull/92) and it's all good, they're not adding anything new or some breaking changes so you can try to update
